### ISSUE TITLE
Getting an error while checking the recommendation feature

### ISSUE THREAD

**Issue by tejalpatel0310** [rukesh-shrestha/Recomendation-System#15]
I am getting issue while checking the recommendations. 

Can you tell me where is responses.text file located or how it is accessed??

![Screenshot (83)](https://user-images.githubusercontent.com/47177855/158957245-28833337-1f10-43cb-a815-7d5496520cf6.png)

**Comment by rukesh-shrestha** [comment]
@tejalpatel0310 responses.json is the file where you train the model and save all the responses in the JSON format. 

For the enhance Recommendation System. You can prefer to my another repo. 
[Repo link](https://github.com/rukesh-shrestha/Book-Recommendation-System)

**Comment by tejalpatel0310** [comment]
Hello Rukesh,

Thank you for your response.
After cloning your project, I am having the error shown in the
attached image while checking the recommendation. Can you please help me
out as soon as possible to solve this problem?

Thank you.

Regards,
Tejal Patel
